# Generated by Django 2.1.2 on 2018-10-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181015_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
